KTEL-21: As a reseller I want my emails to be signed with DKIM so that they are reliably delivered
2600hz/kazoo-teletype pull request #70
Opened 2023-12-27 22:02 UTC by manushiperera

Previously, DKIM information is not used while sending emails. Now, it is using DKIM options which are saved in `whitelabel` document. If there is a `whitelabel `document found for the respective account and DKIM private key file is available, it used to send DKIM signing information over the email.

2023-12-28 20:59 UTC, manushiperera commented
Related PRs:

https://github.com/2600hz/kazoo-crossbar/pull/545
https://github.com/2600hz/kazoo-core/pull/758

2023-12-29 19:32 UTC, icehess requested changes

2023-12-29 19:32 UTC, icehess commented on src/templates/teletype_account_zone_change.erl
> -                                             ,kapi_notifications:account_id(DataJObj)
`kapi_notifications:account_id` is the account_id from the AMQP message. Reading the ticket the request is to use account id from where the template is from. In this case you have to grab it from `TemplateMetaJObj` (but default to `kapi_notifications:account_id` in case is was missing):

```
TemplateAccountId = kz_doc:account_id(TemplateMetaJObj, kapi_notifications:account_id(DataJObj))
```

2024-01-04 22:47 UTC, manushiperera commented on src/templates/teletype_account_zone_change.erl
> -                                             ,kapi_notifications:account_id(DataJObj)
Done

2024-01-12 17:57 UTC, jamesaimonetti commented on src/teletype_util.erl
> +            case kz_json:get_ne_binary_value(<<"pvt_dkim_private_key_id">>, WhiteLabelJObj, 'undefined') of
Use kzd_whitelabel to access these values

2024-01-16 21:57 UTC, manushiperera commented on src/teletype_util.erl
> +            case kz_json:get_ne_binary_value(<<"pvt_dkim_private_key_id">>, WhiteLabelJObj, 'undefined') of
Done

2024-01-26 21:07 UTC, merged